### ISSUE TITLE
Extension keeps unloading itself

### ISSUE THREAD

**Issue by MichaelGOtto** [mohamedmansour/reload-all-tabs-extension#13]
I find every few days the icon for Reload-All-Tabs extn. disappears.  I open my extensions page and it is disabled with option to reload the extension.  Then it works for a few days, few reboots, then again the icon disappears.  Using v. 4.0.1.  Have written about this before but nothing has been done.

**Comment by mohamedmansour** [comment]
Hmm @MichaelGOtto are you referring to the purple icon? I am trying to repro this, any help would be appreciated so I Can fix quickly!

**Comment by MichaelGOtto** [comment]
I haven't seen this in the past few weeks. Before that I used to have the
extn appear disabled and in the extn page it says it has been unloaded. Now
it seems fixed. Thanks

**Comment by MichaelGOtto** [comment]
I just encountered the same issue.  The extension disappeared from my
browser menu.  I returned to my extensions and reloaded the "Reload all
tabs" extn, and the icon returned to it's customary position on my toolbar.

So, Mohamed, I would say that this problem has not been resolved.

Am I the only person reporting this issue?

thanks

michael otto

**Comment by mohamedmansour** [comment]
Something must be wrong with Chrome Extensions Settings Sync :( Every time you goto the options page, and try to change an option it saves it the cloud (that’s the right way doing it) maybe everything is resetted. I noticed that as well.

When this happens next time, can you please goto the options for that extension (right click on the icon > options) and see if anything under context menu is enabled?


________________________________

**Comment by MichaelGOtto** [comment]
Here is a screenshot of my options page.  I had just reloaded the extension
prior to this screenshot.

Is there anything I should change?

Thanks

michael
