### ISSUE TITLE
New context menu options

### ISSUE THREAD

**Issue by Tobblish** [mohamedmansour/reload-all-tabs-extension#15]
Before the new update you could click the option in the context menu.
That no longer works as you have to move the cursor to a new menu that opens up while hovering the text and icon.

I find it unnecessary to have a new menu opening up instead of how it used to be.
A simple click of a button.

**Comment by mohamedmansour** [comment]
Hi @Tobblish, doesn't this works?

![image](https://user-images.githubusercontent.com/68524/42391526-8a7ca0ac-8104-11e8-8c7c-a5699370b2fc.png)

Which options are you referring to?

**Comment by Tobblish** [comment]
@mohamedmansour I'm refering to the right click context menu.
![2018-07-06 19_12_25-new context menu options issue 15 mohamedmansour_reload-all-tabs-extension](https://user-images.githubusercontent.com/8053643/42391656-659b526e-8150-11e8-854e-93af6ae399d7.png)

**Comment by mohamedmansour** [comment]
Ah yes, this is a bug, I Will make it work tonight or in a bit :)

**Comment by Tobblish** [comment]
Awesome!
It threw me completely off having to move the mouse to the right to reloading all tabs.

**Comment by mohamedmansour** [comment]
@Tobblish  do you want me to allow you to remove it? or make it work? the bug is that it doesn't work

**Comment by mohamedmansour** [comment]
ill just remove it

**Comment by Tobblish** [comment]
I would like it to work exactly as before. You pick what kind of action you want for the context menu in options. And remove the new submenu.

**Comment by mohamedmansour** [comment]
I pushed a new version 4.1.1 @Tobblish enjoy! (I think it takes under an hour to push to Google stores)
