### ISSUE TITLE
Remove content script in favor of Commands

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/reload-all-tabs-extension#17]
In order to remove more permissions, and keep supporting keyboard events, we need to remove content scripts and user keyboard events. As explained in this PR #16 

This means keyboard events will not be customizable anymore. I believe this  would be a decent drawback to protect to enhance security.

https://developer.chrome.com/extensions/commands

We could use Ctrl+Shift+R (Command + Shift +R on mac)

**Comment by mohamedmansour** [comment]
> The user is free to designate any shortcut as global using the UI in chrome://extensions \ Keyboard Shortcuts, but the extension developer is limited to specifying only Ctrl+Shift+[0..9] as global shortcuts.

Sweet! This will totally work!

**Comment by mohamedmansour** [comment]
@triplepoint  can you test if your mac works for this setup? (Reload all tabs in the window via keyboard)

**Comment by triplepoint** [comment]
With commit `3aa5ab` installed, I can `Alt + Shift + r` to reload all tabs.
The context menu has a "Reload this window" option that also reloads all tabs.
The extension button in the URL baralso reloads all tabs.

**Comment by mohamedmansour** [comment]
Thank you 🙏Will submit v4.2 to app store!
