### ISSUE TITLE
Suggestion: Toggle to change default action

### ISSUE THREAD

**Issue by BaronKrause** [mohamedmansour/reload-all-tabs-extension#21]
It would be really handy to have a toggle to change the default action from "reload all windows" to "reload this window". I find If I have multiple windows open that I use "reload this window" way more, not wanting to reload a movie or some other window I have open when reloading all my tabs in my current window.

Being able to change its default action would make it way more convenient.

Thanks!

**Comment by mohamedmansour** [comment]
Sounds good

**Comment by equalsJeffH** [comment]
this seems to be related to issue #20 

It seems we need a way for the user to alter the seeting of `this.cachedSettings.reloadAllWindows` ?  (the latter's value defaults to `true`)

**Comment by mohamedmansour** [comment]
@equalsJeffH I believe this is being handled by #32, 

Duplicate of #20

**Comment by mohamedmansour** [comment]
Duplicate of #20

**Comment by mohamedmansour** [comment]
Duplicate of #20
