### ISSUE TITLE
Conflict with "The Great Suspender" extension

### ISSUE THREAD

**Issue by CheckeredFlag** [mohamedmansour/reload-all-tabs-extension#24]
I use "The Great Suspender" extension (v7.1.0) to suspend idle tabs.  Tabs remain suspended until the tab is reloaded and I would expect the "Reload All Tabs" extension (v4.2.0) to unsuspend these tabs via reload.  However, it only unsuspends the active tab, requiring me to reload each tab individually and defeating the purpose of this extension.

I have no idea if this is an issue with this extension or with The Great Suspender.  I thought I'd ask here first.

**Comment by QueenOfStars** [comment]
@CheckeredFlag in Great Suspender options, uncheck "Apply Chrome's built-in memory-saving when suspending" and tabs will reload again with Reload All Tabs. Worked for me anyway, both in Chrome and Iron.

Cheers,
QoS

**Comment by CheckeredFlag** [comment]
Sweet!  Nice workaround.  Confirmed that it works for me too.

**Comment by mohamedmansour** [comment]
@QueenOfStars  and @CheckeredFlag , thank you! Maybe I will add a FAQ to add this workaround in the extension options. Or maybe just implement a suspender option as explained here #28
