### ISSUE TITLE
hello please remove your extension from right click menu

### ISSUE THREAD

**Issue by stocktgs** [mohamedmansour/reload-all-tabs-extension#26]

**Comment by ourtown1** [comment]
Add The Great Suspender to right-click context menu  is an option already see Settings

**Comment by mohamedmansour** [comment]
@stocktgs  you can already do this in settings:
![image](https://user-images.githubusercontent.com/68524/102521859-4c7dc300-404a-11eb-9599-b8d75230e0b5.png)

Is that what you wanted?

**Comment by leao-nardo** [comment]
> @stocktgs you can already do this in settings:
> ![image](https://user-images.githubusercontent.com/68524/102521859-4c7dc300-404a-11eb-9599-b8d75230e0b5.png)
> 
> Is that what you wanted?

looks like this makes it. just a clarification : unchecking all the boxes makes it disappear from the menu-i just tested.
so this issue probably can be closed.

**Comment by mohamedmansour** [comment]
Thanks @leao-nardo , do you think we need to update the text in options?

**Comment by leao-nardo** [comment]
> Thanks @leao-nardo , do you think we need to update the text in options?

yeah, can be good to add the clarification there to be clear
