### ISSUE TITLE
Extension no longer works with current version of Chrome

### ISSUE THREAD

**Issue by MMM850307** [mohamedmansour/reload-all-tabs-extension#46]
Extension no longer works with version 91.0.xxxx.xxx.

**Comment by mohamedmansour** [comment]
Maybe another extension is conflicting? It is still working, can you try disabling other extensions and see if this one works?

**Comment by MMM850307** [comment]
It doesn't look like it's just my chrome version, but if you read the comments in the Chrome web store, lots of others are having issues...

Do you know of any specific conflicting extensions? I'll try to disable my extensions and see if it'll work again...

Thanks for the prompt response regardless...

**Comment by mohamedmansour** [comment]
Interesting, it must be something went wrong in updates that corrupted the extension between v90 and v91. If you still have it in broken state, I would love if you can help me debug why.

If you visit this (copy paste this in chrome):
chrome://extensions/?id=midkcinmplflbiflboepnahkboeonkam

And (toggle dev button on top right
![image](https://user-images.githubusercontent.com/68524/125405220-56f80500-e36c-11eb-8ef0-3e67beee838c.png)

Click on service worker and see if errors appear:
![image](https://user-images.githubusercontent.com/68524/125405247-5fe8d680-e36c-11eb-9e9e-647d3744a842.png)

**Comment by elec2** [comment]
Hey, after having the same problem for the last couple of weeks i decided to reinstall the extension and voila.... everything is working again. The problem occurred in my chrome browser around the switch from v.99 to v.100 i think.

**Comment by mohamedmansour** [comment]
Thank you! if anyone gets this issue, let me know, please open a new issue with proper error logs
