### ISSUE TITLE
Hard-refresh (Shift-F5) functionality

### ISSUE THREAD

**Issue by jessewebb** [mohamedmansour/reload-all-tabs-extension#5]
The main reason I use this extension to aid me in developing websites. I often change some HTML and/or CSS and then want to refresh all my tabs to take a quick glance at all the website's pages.

Unfortunately, this plugin only does a "soft" refresh of the page and chrome re-uses any cached copies of linked resources (e.g. CSS files). This forces me to have to "hard" refresh the pages manually to see my updates to the CSS files.

It would be nice if this extension allowed hard-refreshes. Holding the Shift key and clicking on Chrome's refresh button does a hard-refresh, I would suggest that you make Shift-clicking your extension's button do the same for all tabs. Also consider allowing a second shortcut for doing either a soft or hard refresh of all tabs.

On a side note, I think it is a bad idea to use Ctrl+Shift+R as the default shortcut. In firefox, this shortcut already exists (it does a hard-refresh of the current tab as opposed to Ctrl+R only doing a soft refresh). This even further strengthens my point that the Shift key is usually associated with performing a hard refresh. I would suggest you consider changing the default shortcut to use "Alt" instead of "Shift" as the second modifier. This way, Ctrl+Alt+R could do a soft refresh of all tabs and Ctrl+Alt+Shift+R could do the hard equivalent. Since these shortcuts are not used in Firefox yet, they could become standardized across both browsers so that users wouldn't have to remember two sets of different shortcuts for the same functionality between browsers. Just a thought.

**Comment by mohamedmansour** [comment]
It has been YEARS for this bug, But I believe i fixed it last year. You can change the default keyboard short cut and allow HARD Refresh in settings!
