### ISSUE TITLE
Difficult-to-See Icon

### ISSUE THREAD

**Issue by SoCalDude** [mohamedmansour/reload-all-tabs-extension#9]
When I use a dark theme in Chrome the Reload-All-Tables icon is very difficult to see. Could we have an icon option between a dark (blue, as it is presently) and light (white, yellow, etc)? Or maybe just keep the one icon, but make it much lighter. Thanks!

See partial screenshot below ...

![2016-11-04-11-20-00](https://cloud.githubusercontent.com/assets/7506541/20017526/45c68a12-a281-11e6-99b1-d8629b8c749a.png)
[https://i.imgur.com/HcIJUZ6.png](url)

**Comment by mohamedmansour** [comment]
@SoCalDude Hmm interesting, let me figure out a proper solution, perhaps make it customizable :)

**Comment by mohamedmansour** [comment]
@erensong lets figure out a dark/light friendly icon color
